.\n8n\scripts\update-gemini-key.ps1param(
    [switch]$FromDashboard
)

$ErrorActionPreference = "Stop"
. "$PSScriptRoot\_lib.ps1"

$root = Get-RootDir
$envFile = Join-Path $root ".env"
$dashboardEnv = Join-Path $root "dashboard\.env.local"
$example = Join-Path $root "dashboard\.env.local.example"

if (-not (Test-Path $envFile)) {
    throw ".env not found. Copy .env.example to .env first."
}

$envMap = Get-EnvMap -EnvFile $envFile
$apiKey = $envMap["N8N_API_KEY"]

if ([string]::IsNullOrWhiteSpace($apiKey) -and (Test-Path $dashboardEnv)) {
    $dashMap = Get-EnvMap -EnvFile $dashboardEnv
    if (-not [string]::IsNullOrWhiteSpace($dashMap["N8N_API_KEY"])) {
        $apiKey = $dashMap["N8N_API_KEY"]
        $lines = Get-Content $envFile
        $updated = $false
        $newLines = foreach ($line in $lines) {
            if ($line -match '^\s*N8N_API_KEY\s*=') {
                $updated = $true
                "N8N_API_KEY=$apiKey"
            }
            else {
                $line
            }
        }
        if (-not $updated) {
            $newLines += "N8N_API_KEY=$apiKey"
        }
        $newLines | Set-Content -Path $envFile -Encoding utf8
        Write-Host "Copied N8N_API_KEY from dashboard/.env.local into root .env"
    }
}

if ([string]::IsNullOrWhiteSpace($apiKey)) {
    $apiKey = Get-N8nApiKey
}

if ([string]::IsNullOrWhiteSpace($apiKey)) {
    Write-Warning "N8N_API_KEY is empty - create one in n8n Settings > API"
}

$envMap = Get-EnvMap -EnvFile $envFile
$n8nPublic = if ($envMap["NEXT_PUBLIC_N8N_URL"]) { $envMap["NEXT_PUBLIC_N8N_URL"] } else { "http://localhost:5678" }
$kitName = if ($envMap["NEXT_PUBLIC_KIT_NAME"]) { $envMap["NEXT_PUBLIC_KIT_NAME"] } else { "S-C Automation Kit" }

$outLines = @(
    "# Auto-generated by sync-dashboard-env.ps1 - safe to edit",
    "",
    "N8N_API_KEY=$apiKey",
    "N8N_INTERNAL_URL=http://localhost:5678",
    "NEXT_PUBLIC_N8N_URL=$n8nPublic",
    "NEXT_PUBLIC_KIT_NAME=$kitName"
)

if (-not (Test-Path $dashboardEnv) -and (Test-Path $example)) {
    Write-Host "Creating dashboard/.env.local from template values."
}

$outLines | Set-Content -Path $dashboardEnv -Encoding utf8
Write-Host "Synced dashboard/.env.local"
